# Generated by Django 4.1.2 on 2022-10-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_history_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='name',
            field=models.CharField(blank=True, max_length=2056, null=True),
        ),
    ]
